name: nn-driving
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.0.2u=h7b6447c_0
  - pip=22.3.1=py37h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.7.0=h6e4f718_3
  - readline=7.0=h7b6447c_5
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.14=h993c535_1
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==1.0.0
      - appdirs==1.4.3
      - appnope==0.1.2
      - argon2-cffi==21.1.0
      - arrow==0.15.5
      - async-generator==1.10
      - attrs==19.3.0
      - autobahn==17.10.1
      - automat==0.8.0
      - backcall==0.2.0
      - backports-abc==0.5
      - backports-shutil-get-terminal-size==1.0.0
      - bcrypt==3.1.7
      - bleach==4.1.0
      - blinker==1.4
      - cachetools==4.2.4
      - catkin-pkg==1.0.0
      - cbor==1.0.0
      - certifi==2019.11.28
      - cffi==1.15.0
      - chardet==3.0.4
      - click==7.0
      - colorama==0.4.3
      - configobj==5.0.6
      - configparser==5.0.2
      - constantly==15.1.0
      - cryptography==2.8
      - cycler==0.11.0
      - cython==0.29.14
      - dataclasses==0.6
      - dbus-python==1.2.16
      - decorator==4.4.2
      - defusedxml==0.7.1
      - distlib==0.3.3
      - distro==1.4.0
      - docutils==0.16
      - empy==3.3.2
      - entrypoints==0.3
      - enum34==1.1.10
      - fasteners==0.14.1
      - filelock==3.0.12
      - fonttools==4.38.0
      - future==0.18.2
      - glfw==2.0.0
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.41.1
      - h5py==2.10.0
      - html5lib==1.0.1
      - httplib2==0.14.0
      - hyperlink==19.0.0
      - idna==2.8
      - imageio==2.31.2
      - importlib-metadata==2.0.0
      - incremental==16.10.1
      - ipy==1.0
      - ipykernel==5.3.4
      - ipython==7.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - jedi==0.18.0
      - jinja2==3.1.6
      - joblib==1.1.0
      - jsonpatch==1.28
      - jsonpointer==2.0
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==6.1.7
      - jupyter-console==6.2.0
      - jupyter-core==4.6.3
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.0
      - keyring==18.0.1
      - kiwisolver==1.3.2
      - launchpadlib==1.10.13
      - lazr-restfulclient==0.14.2
      - lazr-uri==1.0.3
      - lockfile==0.12.2
      - macaroonbakery==1.3.1
      - mako==1.1.0
      - markdown==3.3.3
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - metaconfig==0.1.4a1
      - mistune==0.8.4
      - monotonic==1.5
      - more-itertools==4.2.0
      - mpi4py==3.0.3
      - mplcursors==0.4
      - nbclient==0.5.1
      - nbconvert==6.0.7
      - nbformat==5.0.8
      - nest-asyncio==1.5.1
      - netifaces==0.10.4
      - networkx==2.6.3
      - nose==1.3.7
      - notebook==6.1.5
      - numpy==1.20.3
      - numpy-stl==3.1.2
      - oauthlib==3.1.0
      - olefile==0.46
      - opencv-python==4.5.4.58
      - packaging==24.0
      - pandas==0.25.3
      - pandocfilters==1.4.3
      - paramiko==2.6.0
      - parso==0.8.2
      - pathlib2==2.3.5
      - pbr==6.1.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkginfo==1.7.0
      - plyvel==1.2.0
      - prettytable==0.7.2
      - prometheus-client==0.12.0
      - prompt-toolkit==3.0.22
      - protobuf==3.14.0
      - psutil==5.5.1
      - ptyprocess==0.7.0
      - py-ubjson==0.14.0
      - pyasn1==0.4.2
      - pyasn1-modules==0.2.1
      - pycairo==1.16.2
      - pycparser==2.21
      - pycryptodomex==3.6.1
      - pycups==1.9.73
      - pydot==1.4.1
      - pygments==2.10.0
      - pyhamcrest==1.9.0
      - pyjwt==1.7.1
      - pymacaroons==0.13.0
      - pynacl==1.3.0
      - pyopengl==3.1.0
      - pyopenssl==19.0.0
      - pyparsing==3.0.5
      - pyqrcode==1.2.1
      - pyqt5==5.14.1
      - pyqt5-sip==12.13.0
      - pyrfc3339==1.1
      - pyrsistent==0.18.0
      - python-dateutil==2.7.3
      - python-gnupg==0.4.5
      - python-snappy==0.5.3
      - python-utils==3.5.2
      - pytrie==0.2
      - pytz==2019.3
      - pywavelets==1.2.0
      - pyxdg==0.26
      - pyyaml==5.3.1
      - pyzmq==22.3.0
      - qtconsole==4.7.7
      - qtpy==1.9.0
      - rawpy==0.18.1
      - requests==2.25.1
      - requests-oauthlib==1.3.0
      - requests-toolbelt==0.9.1
      - requests-unixsocket==0.2.0
      - roman==2.0.0
      - rosdistro==0.8.3
      - rospkg==1.3.0
      - rsa==4.7.2
      - ruamel-yaml==0.15.89
      - scandir==1.10.0
      - scikit-image==0.16.2
      - scikit-learn==0.22.2.post1
      - scipy==1.6.3
      - secretstorage==2.3.1
      - send2trash==1.8.0
      - service-identity==18.1.0
      - simplegeneric==0.8.1
      - simplejson==3.16.0
      - singledispatch==3.6.1
      - six==1.14.0
      - tensorboard==2.4.0
      - tensorboard-plugin-wit==1.7.0
      - terminado==0.12.1
      - testpath==0.5.0
      - testresources==2.0.2
      - torch==1.8.1
      - torchfile==0.1.0
      - torchsummary==1.5.1
      - torchvision==0.9.1
      - tornado==6.1
      - tqdm==4.51.0
      - traitlets==5.1.1
      - transforms3d==0.3.1
      - ttach==0.0.3
      - twisted==18.9.0
      - txaio==2.10.0
      - typing-extensions==3.7.4.3
      - u-msgpack-python==2.1
      - urllib3==1.26.5
      - virtualenv==20.4.7
      - visdom==0.1.8.9
      - wadllib==1.3.3
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.2.1
      - werkzeug==2.0.2
      - widgetsnbextension==3.5.2
      - wsaccel==0.6.2
      - zipp==1.0.0
      - zope-interface==4.7.1
prefix: /home/faizaladin/anaconda3/envs/nn-driving
